"""Initial migration

Revision ID: 4094f41eec72
Revises: 
Create Date: 2025-01-07 12:37:38.930015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4094f41eec72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patterns',
    sa.Column('pattern_part', sa.Enum('toe', 'middle', 'heel', 'cuff', name='pattern_part'), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pattern_part')
    )
    op.create_unique_constraint('unique_knit_size', 'stitchcount', ['knit_size'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_knit_size', 'stitchcount', type_='unique')
    op.drop_table('patterns')
    # ### end Alembic commands ###
